[files]
extend-exclude = [".git/", "*.bin"]
ignore-hidden = true


[default]
extend-ignore-words-re = [
  # Ignore any words that is smaller than 3 characters
  # since those are typically abbreviations
  '^[a-zA-Z]{1,3}$',
]

extend-ignore-re = [
  "\\b[0-9A-Za-z+/]{91}(=|==)?\\b",  # base64 strings
  "[0-9a-fA-F]{7,}",                 # git commit hashes
  "\\b[0-9A-Za-z+/]{33,}(=|==)?\\b", # SHA/tpub/adresses etc strings
]

[type.gitignore]
check-file = false
extend-glob = [".gitignore"]
