# Generated by Hermit; START; DO NOT EDIT.
if status is-interactive
  set -q HERMIT_ROOT_BIN; or set HERMIT_ROOT_BIN $HOME/bin/hermit
  if test -x $HERMIT_ROOT_BIN
    source $__fish_config_dir/functions/hermit_help.fish
  end
end
# Generated by Hermit; END; DO NOT EDIT.
