if [ -r "$HOME/.config/shell/environment" ]; then
  . "$HOME/.config/shell/environment"
fi

case $- in
  *i*) ;;
  *) return ;;
esac

# Get the directory of this file, following its symlink when needed.
CURR_FILE=${BASH_SOURCE[0]}
if [ -L "$CURR_FILE" ]; then
  CURR_FILE=$(readlink "$CURR_FILE")
fi
CURR_FILE_DIR=$(cd "$(dirname "$CURR_FILE")" && pwd)

source "$CURR_FILE_DIR/shellrc.bash"

unset CURR_FILE CURR_FILE_DIR

export STM32_PRG_PATH=/home/hjz/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin