source ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc

#*****************CURR_FILE_DIR*****************
# Get directory of current script file, follow symlink if needed.
CURR_FILE="${(%):-%N}"
if [ -L ${CURR_FILE} ]; then
	CURR_FILE=`readlink ${CURR_FILE}`
fi
CURR_FILE_DIR="$(cd "$(dirname "${CURR_FILE}" )" && pwd )"
#*****************CURR_FILE_DIR*****************
source ${CURR_FILE_DIR}/shellrc.zsh
unset CURR_FILE_DIR

zstyle ':completion:*' accept-exact '*(N)'

__git_files () {
    _wanted files expl 'local files' _files
}

unsetopt CORRECT                      # Disable autocorrect guesses. Happens when typing a wrong
                                      # command that may look like an existing one.

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

if [ -f ~/.fzf.zsh ]; then
  export FZF_DEFAULT_COMMAND='fd --type file'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# enable autocomplete function
autoload -U compinit
compinit


# BEGIN opam configuration
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
[[ ! -r '/Users/hjz/.opam/opam-init/init.zsh' ]] || source '/Users/hjz/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null
# END opam configuration
